---
- name: Test Vault Variables
  hosts: database_servers
  gather_facts: yes
  vars_files:
    - "../vars/{{ environment_name }}/vault.yml"
  
  tasks:
    - name: Display all vault variables
      debug:
        msg: |
          Environment: {{ environment_name | default('not set') }}
          Admin password defined: {{ vault_march_db_password is defined }}
          Postgres password defined: {{ vault_postgres_password is defined }}